### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by Faunsce** [LPGhatguy/rojo#144]
Specify the difference in usage of  `Properties` and `$properties` especially since the misuse of `Properties` in a `model.json` can significantly increase the amount of work needed when creating an object using that format. Example below. The ability to use strict vs loose typing is nice but it should be highlighted as many may come to think that `model.json` requires strict type and your default.project.json requires a more loose type. Also, what is the purpose oh having `$className` and `ClassName` instead of just one or the other? If neither are different why not deprecate or outright remove one of them?
```json
{
  "Name": "Block",
  "$classname": "Part",
  "Properties": {
    "Anchored": {
      "Type": "Bool",
      "Value": true
    }
  }
}
```
`versus`
```json
{
  "Name": "Block",
  "$classname": "Part",
  "$properties": {
    "Anchored": true
  }
}
```

**Comment by Faunsce** [comment]
After some experimenting, if you use `$properties` instead of `Properties` nothing errors in the json but you dont actually create the "block" properly either. Can we then be able to use one of the other to specify how we will "Type" that specific `model.json` or better yet, allow us to specify per property "Typing"?

**Comment by LPGhatguy** [comment]
Dollar sign prefixed attributes are in the project file only. They're named like that because everything that *doesn't* start with a dollar sign is supposed to be a child instance!

Meanwhile, the .model.json format uses strictly PascalCase members and fully-qualified property values. It's mostly to keep compatibility with Rojo 0.4.x, but could definitely be documented more thoroughly.

The project format has a detailed breakdown page as to what's allowable in the documentation, which should clear up any confusion for that specifically.

**Comment by Faunsce** [comment]
Are there any plans or is it even possible for eventually a more loose typing to be allowed in model.json? I would enjoy having to use far less lines for each property of things i generate using it

**Comment by LPGhatguy** [comment]
Absolutely! There was an issue filed for this back when .model.json files were introduced, #31.

Improvements for .model.json files have kind of been on hold while I've been fleshing out support for rbxmx and rbxm files, which solve a lot of the same problems that people would normally use Rojo's cusotm model format for.
