### ISSUE TITLE
Option to preserve unknown instances inside Rojo instances

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/rojo#182]
Even with `$ignoreUnknownInstances`, the following scenario happens:

1. Have an existing place with
```
ReplicatedStorage
L Items
  L Sword
    L SwordModel
```

2. Have the following in `.project.json`
```
{
  "name": "git",

  "tree": {
    "$className": "DataModel",

    "ReplicatedStorage": {
      "$className": "ReplicatedStorage",
      "$ignoreUnknownInstances": true,
      "$path": "src/ReplciatedStorage",
    }
  }
}
```

3. Have this data structure
```
src/
L Items
  L Sword
    L SwordScript.lua
```

4. Sync
5. SwordModel disappears

---

This is intentional behavior, but for a lot of developers this does not work with them. While you *could* just repeatedly make new pathways in the tree, this is inconvenient, and makes it harder to convince new developers to use Rojo. I believe you should be able to configure Rojo to not delete SwordModel, and just edit the `SwordScript` ModuleScript. Rofresh did this by using an internal CollectionService tag. Rojo could do the same if you use an explicit option.

This is especially important to me, so if this is in line with Rojo's vision I would be willing to work on this.

**Comment by LPGhatguy** [comment]
As we've talked about, `$ignoreUnknownInstances` only works on direct children!

I'm open to the idea of renaming `$ignoreUnknownInstances` to something like `$ignoreUnknownChildren` (hm) and introducing `$ignoreUnknownDescendants`, which should fix a case like this in the broad sense.

It'll still have the problem where stuff that was deleted while Rojo wasn't running won't be deleted. I'm not fond of the idea of using Rofresh's tag approach here, since I think it's really valuable for Rojo to be stateless. It means that whenever there's a bug in syncing, you can likely restart the server or client and continue on your way.

Another setting we could introduce that's more specific is having Rojo specifically ignore anything that isn't a script. This _doesn't_ solve the problem where you're trying to make tools, where the container instance won't be a `Folder`, but might be a good workaround to get projects like this up-and-running.

**Comment by Kampfkarren** [comment]
> It'll still have the problem where stuff that was deleted while Rojo wasn't running won't be deleted. 
I feel this is a fine behavior.

> Another setting we could introduce that's more specific is having Rojo specifically ignore anything that isn't a script. 
Would this be for pre-Rojo projects that consist of only scripts? Also, I fail to see how tools relate to this.

**Comment by LPGhatguy** [comment]
This was mostly solved by the `.meta.json` work, right?

**Comment by Kampfkarren** [comment]
Yep.

**Comment by Seniate** [comment]
Is it still a possibility for something along the lines of $ignoreUnknownDescendants being implemented?

**Comment by Dekkonot** [comment]
It's a possibility, though you'd want to either look for an existing issue on it or open a new one. We're all too aware of how cumbersome it is to set `ignoreUnknownInstances` for a bunch of things, so a toggle for descendants is very much on the table.
