### ISSUE TITLE
Handle team create

### ISSUE THREAD

**Issue by Quenty** [LPGhatguy/rojo#25]
Need to set CurrentEditor for stuff being synced, so make team create obvious

**Comment by LPGhatguy** [comment]
The more I think about this the more I feel that Rojo and team create are mutually exclusive.

**Comment by evaera** [comment]
http://wiki.roblox.com/index.php?title=API:Class/LuaSourceContainer/CurrentEditor

CurrentEditor is not accessible with Lua so this probably isn't possible :(

**Comment by LPGhatguy** [comment]
I'm going to go ahead and close this issue. I think the general stance of Rojo is that it's more or less incompatible with team create, since even with two-way sync, it's kind of fuzzy what Rojo would be able to do to work around someone else working on a script.

If we ever get a better idea of how to integrate the two, I'm down, but more and more I think Rojo is going to be best paired with a traditional CI/CD pipeline (`rojo upload`) and places per developer.
