### ISSUE TITLE
Support Different Types of Values without using model json

### ISSUE THREAD

**Issue by gamenew09** [LPGhatguy/rojo#28]
From what I can tell the only way to create value objects that aren't ``StringValues`` is to create a model.json file (Although the version I'm currently using, ``0.3.1``, doesn't support model.json). Could you support specifying a value type in the file (probably in json format) or the filename?

One way you could indicate a different value type is to append a ``.type`` at the end of the file name. So if you wanted an IntValue, you could have a filename of ``TestValue.int`` for example.

**Comment by Quenty** [comment]
If we were going to do this, it should still be TestValue.IntValue.json. 

IIRC though, you can set model.json to have a classname. 

I'd much rather not have the type of the value created encoded in the name of the file. Especially since I'd rather have certain models be 1 JSON object instead of multiple files (which gets nasty very quickly).

**Comment by LPGhatguy** [comment]
The JSON format in `.model.json` files is mostly a holdover until proper rbxmx/rbxlx support is implemented. Once we have real model files (and bi-directional syncing) it won't be as big of a deal what the actual on-disk representation is.

I pushed up a [prerelease for 0.4.0](https://github.com/LPGhatguy/rojo/releases/tag/v0.4.0-pre1) that supports `.model.json` files. The only example right now is [this file](https://github.com/LPGhatguy/rojo/blob/master/test-project/src/hello.model.json).

Long-term, I'd like to throw an error or just ignore files that can't be interpreted instead of turning them into StringValue objects like they are right now. To regain the current behavior of StringValue objects, you'd configure some optional plugin!

**Comment by LPGhatguy** [comment]
I think this use case is well-handled by JSON models as well as Rojo's rbxmx and rbxm support!

Since I don't think there's a lot of value in specifying class name via file name only, I'm going to close this issue.
