### ISSUE TITLE
Argument 1 missing or nil

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/rojo#35]
I'm trying to use rojo. When I start the server and press Sync In, I get this error.

> Syncing from server...
> 21:24:25.214 - Argument 1 missing or nil
> 21:24:25.214 - Argument 1 missing or nil
> 21:24:25.215 - Stack Begin
> 21:24:25.216 - Script 'Plugin_1211549683.Rojo.Reconciler', Line 265 - field reconcileRoute
> 21:24:25.216 - Script 'Plugin_1211549683.Rojo.Plugin', Line 120 - method _pull
> 21:24:25.216 - Script 'Plugin_1211549683.Rojo.Plugin', Line 172
> 21:24:25.217 - Stack End

This is my rojo.json

```
{
  "name": "battle-hats",
  "servePort": 8000,
  "partitions": {
    "game": {
      "path": "",
      "target": ""
    }
  }
}
```

**Comment by LPGhatguy** [comment]
My watching settings were messed up, so I missed this, sorry!

Is this the current Git master version or the currently released version?

I've definitely never tested with an empty `path` in a partition, you probably need to point it to a folder like `src` so that `rojo.json` isn't included, anyways.

**Comment by Kampfkarren** [comment]
I was using the version on cargo.

**Comment by LPGhatguy** [comment]
I rewrote the file in question since the current release.

I think I'll be publishing that new version (0.4.0) tonight, which should finish up this bug, which is for 0.3.x!

**Comment by LPGhatguy** [comment]
0.4.0 is finally released and this should no longer be relevant. Thanks for the report!
