### ISSUE TITLE
Fail louder when server and plugin is out of sync

### ISSUE THREAD

**Issue by kbarber** [LPGhatguy/rojo#77]
Until you get stable and parity is no longer an issue, I'd recommend failing loudly when the server and plugin are out of sync. It will save you from support issues, and you'll need this when you go to 0.5.0 anyway I presume in some form.

I just noticed I was running 0.4.5 as the server while running 0.4.9 as the plugin for example after I bumped the lot to 0.4.10. I'd rather just be told to fix it straight away.

Just a thought anyway, feel free to disregard.

**Comment by LPGhatguy** [comment]
The clients should _technically_ be compatible with multiple server versions -- that's what the `protocolVersion` field is in the initial handshake in both 0.4.x and 0.5.0.

Initially, the plan was to let the version numbers drift between the two, since the majority of releases have no server changes other than a version bump. Since I build new binaries and publish everything every release anyways, I'm not sure how valuable that is.

Do you think that Rojo should require that the plugin and server have the exact same version? What about across fix releases? Should we be afraid of not being able to release a plugin without a corresponding server, or vice-versa?

One way to solve this would be to make the server install the plugin for you, but I'm deathly afraid of messing that up and causing a difficult-to-repair installation.

**Comment by LastTalon** [comment]
It would be awkward to prevent different versions from interacting simply because they have a different version number. While its still unstable it should probably just warn, but once a more stable release is available, it would probably be good for each protocol version to know which versions its backward compatible with, which possibly means giving the communication protocol its own version separate from the plugin or file utility version.

**Comment by LPGhatguy** [comment]
Right, that lines up with how Rojo is right now. The protocol is very stable between releases, and made the move from `0` to `1` with the release of 0.4.0. When 0.5.0 is released, the protocol will be bumped to `2`, and an error will be thrown if you try to mismatch clients.

**Comment by kbarber** [comment]
No worries, I'm gonna close this, sounds unnecessary to be tracked.
