### ISSUE TITLE
Rojo should have an option to wipe unknown objects from partition targets, rather than doing it by default

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/rojo#83]
My game has a large codebase where the locations of scripts isn't necessarily exclusive to just scripts. Also, these scripts will regularly contain non-script children (such as tools to clone in). In order to use rojo I'd have to completely change my entire codebase so that neither of these are true.

Model JSON files don't cut it, as they'd quickly become very large depending on what's inside the script, and model JSON files will never be able to compensate for Unions.

I propose an option when specifying partition targets or something similar to not wipe unknown objects and instead just sync back and forth known scripts. 

Possibly part of #26.

**Comment by LPGhatguy** [comment]
The design of Rojo isn't conducive to trying to ignore things that are "unknown", since there's no state kept in the place to determine what things _are_ known. @OsyrisRblx had different thoughts on that when he started [Rofresh](https://github.com/osyrisrblx/rofresh), and so it uses tags to keep some state inside your place file.

I think this sort of functionality is almost completely replaced by two-way sync, and in the cases where it isn't, #33 would go a long way in helping.

In general, mixing script and non-script things in the same place is going to make it really hard to version a place file accurately.

**Comment by Kampfkarren** [comment]
By two way sync, do you expect that to bring over model JSON files? If so, I suppose that's a good alternative EXCEPT for Unions, where it's all binary data.

**Comment by LPGhatguy** [comment]
I'm hoping to sync out JSON _and_ rbxm/rbxmx models eventually.

Unions are problematic; I'm hoping to push internally for an API to get union data out effectively so that I can serialize them in some way. Same problem goes for any other objects that are opaque to scripts.

**Comment by Kampfkarren** [comment]
That sounds good. I like the idea of model JSON files (so long as they export for me) because it means the git diffs for my game will show more than just my scripts, but I'm just worried that I'll have to separate everything from outside of childs as my scripts. I'm going to keep this issue up just to show the problem I'm having, but you can feel free to close it if there's a more appropriate issue for it.

**Comment by LPGhatguy** [comment]
This should be up and working now in 0.5.0 as `$ignoreUnknownInstances`!
