### ISSUE TITLE
Rojo requires Microsoft Visual C++ 2015 Redistributable Update 3, but does not note this anywhere.

### ISSUE THREAD

**Issue by Nimblz** [LPGhatguy/rojo#89]
As the title says, rojo requires Microsoft Visual C++ 2015 Redistributable Update 3.
If this is not installed on the user's system, they will get an error noting that VCRuntime140.dll is missing.
An easy fix for this is noting that Visual C++ 2015 Update 3 is required to run Rojo in the Installation section of the docs.

**Comment by LPGhatguy** [comment]
I wonder how much of this is actually just incidental from the machine I use to build the releases!

It's totally possible that Rojo might start requiring the VC++ 2017 Redistributable someday just because I got rid of my 2015 install, for example.

I'll take a deeper look over the next couple weeks and see if I can pin that down before adding it to the docs. Maybe the solution would be to statically link the CRT?
